/*
Plan
| Поле                                     | Что это                          | Когда и чем заполняется                     | Где в коде                                                    |
| ---------------------------------------- | -------------------------------- | ------------------------------------------- | ------------------------------------------------------------- |
| `id` `Int @id @default(autoincrement())` | Внутренний ID плана              | При создании                                | `PrismaPlanCommandRepository.createPlan`                      |
| `title` `String`                         | Название тарифа                  | Из входного DTO                             | `PlanService.createPlan` → `createPlan`                       |
| `description` `String`                   | Описание тарифа                  | Из DTO                                      | Там же                                                        |
| `stripeProductId` `String`               | ID продукта в Stripe             | Возвращается Stripe при создании плана/цены | `PlanService.createPlan`: из `stripePlan.product?.toString()` |
| `stripePlanId` `String`                  | ID «плана/цены» в Stripe         | Возвращается Stripe                         | `PlanService.createPlan`: `stripePlan.id`                     |
| `price` `Float`                          | Стоимость                        | Из входного DTO                             | `PrismaPlanCommandRepository.createPlan`                      |
| `currency` `String`                      | Валюта                           | Из входного DTO                             | Там же                                                        |
| `interval` `String`                      | Интервал (`day/week/month/year`) | Из входного DTO                             | Там же                                                        |
| `paypalProductId` `String`               | ID продукта в PayPal             | Возвращается PayPal                         | `PlanService.createPlan`: `paypalProduct.id`                  |
| `paypalPlanId` `String`                  | ID плана в PayPal                | Возвращается PayPal                         | `PlanService.createPlan`: `paypalPlan.id`                     |
| `createdAt` `DateTime @default(now())`   | Дата создания                    | БД                                          | —                                                             |
| `Subscription Subscription[]`            | Подписки по этому плану          | Связь                                       | —                                                             |

Subscription
| Поле                                     | Что это                                | Когда и чем заполняется / обновляется                                                                                                                                                                                           | Где в коде                                                                                                                                                                                                         |
| ---------------------------------------- | -------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `id` `Int @id @default(autoincrement())` | Внутренний ID подписки                 | Создаётся при вставке                                                                                                                                                                                                           | `PrismaSubscriptionCommandRepository.createSubscription`                                                                                                                                                           |
| `userId` `String`                        | ID пользователя                        | Ставится при создании подписки (из metadata/ custom\_id вебхуков)                                                                                                                                                               | Stripe: `WebhookStripeService.handleSuccessCheckoutSession`.<br>PayPal: `WebhookPaypalService.handleSubscriptionActivated`                                                                                         |
| `planId` `Int`                           | ID плана из нашей таблицы `plans`      | Ставится при создании (берётся из metadata/custom\_id)                                                                                                                                                                          | Те же методы                                                                                                                                                                                                       |
| `createdAt` `DateTime`                   | Дата начала оплаченного периода        | Stripe: первая оплата — `new Date(session.created * 1000)`;<br>PayPal: `new Date(resource.create_time)`                                                                                                                         | Stripe: `handleSuccessCheckoutSession`.<br>PayPal: `handleSubscriptionActivated`                                                                                                                                   |
| `expiresAt` `DateTime`                   | Дата окончания периода                 | Вычисляется как `createdAt + planIntervalsInDays[plan.interval]` (**Stripe первая оплата**, PayPal) или берётся из `invoice.period_end` при продлении (Stripe)                                                                  | Stripe: `handleSuccessCheckoutSession` (create), `handleInvoicePaymentSucceeded` (update).<br>PayPal: `handleSubscriptionActivated` (create), `handlePaymentCompleted` (update — при продлении)                    |
| `stripeSubscriptionId` `String?`         | Внешний ID подписки (Stripe `sub_...`) | Устанавливается на первом успешном платеже                                                                                                                                                                                      | `WebhookStripeService.handleSuccessCheckoutSession` → `createSubscription({ stripeSubscriptionId: session.subscription })`                                                                                         |
| `paypalSubscriptionId` `String?`         | Внешний ID подписки PayPal             | Устанавливается при `BILLING.SUBSCRIPTION.ACTIVATED`                                                                                                                                                                            | `WebhookPaypalService.handleSubscriptionActivated`                                                                                                                                                                 |
| `isAutoRenewal` `Boolean @default(true)` | Наш флаг автопродления                 | — Stripe: меняется через API (`subscriptions.update(cancel_at_period_end)`) и затем в БД;<br>— PayPal: включение/выключение через `activateSubscription/suspendSubscription` + отражение в БД по вебхукам `SUSPENDED/ACTIVATED` | Изменение по запросу пользователя: `SubscriptionService.autoRenewalSubscription`.<br>Отражение по вебхукам: PayPal — `handleSubscriptionSuspended` (false); Stripe — флаг меняется через `autoRenewalSubscription` |
| `plan` `Plan @relation`                  | Связь на план                          | Заполняется Prisma автоматически по `planId`                                                                                                                                                                                    | —                                                                                                                                                                                                                  |
| `deletedAt` `DateTime?`                  | Мягкое удаление подписки               | Ставитcя при «удалении» (например, после `invoice.payment_failed` в Stripe — отмена и чистка)                                                                                                                                   | Stripe: `WebhookStripeService.handleInvoicePaymentFailed` → `subscriptionService.deleteSubscription`.<br>PayPal: `handleSubscriptionExpired`                                                                       |

Transaction
| Поле                                           | Что это                                                                          | Когда и чем заполняется / обновляется                                                                                                                                                                                                      | Где в коде                                                                                                                                                                                                                                                                                                                      |
| ---------------------------------------------- | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `id` `Int @id @default(autoincrement())`       | Внутренний ID транзакции в нашей БД                                              | Создаётся Prisma при вставке                                                                                                                                                                                                               | `TransactionCommandRepository.createTransaction`                                                                                                                                                                                                                                                                                |
| `amount` `Float`                               | Сумма платежа (в базовой валюте плана)                                           | Ставится из `plan.price` при создании транзакции                                                                                                                                                                                           | `TransactionCommandRepository.createTransaction`                                                                                                                                                                                                                                                                                |
| `currency` `String`                            | Валюта (ISO-код, напр. `usd`)                                                    | Ставится из `plan.currency` при создании                                                                                                                                                                                                   | `TransactionCommandRepository.createTransaction`                                                                                                                                                                                                                                                                                |
| `stripeSubscriptionId` `String?`               | Внешний ID подписки в Stripe (например, `sub_...`)                               | **Stripe:**<br>— при первой успешной оплате (событие `checkout.session.completed`) кладётся из `session.subscription` **в апдейте транзакции**;<br>— при автосписаниях (`invoice.payment_*`) пишется в **новые** транзакции SUCCESS/FAILED | Установка на первом платеже: `WebhookStripeService.handleSuccessCheckoutSession` → `transactionService.updateTransaction(... { stripeSubscriptionId })`.<br>При автосписании: `handleInvoicePaymentSucceeded/Failed` → `transactionService.createTransaction(... stripeSubscriptionId)`                                         |
| `stripeSessionId` `String?`                    | ID Checkout Session (`cs_...`) или у инвойса — `invoice.id` при автосписании     | **Stripe:**<br>— при инициации оплаты мы сначала создаём Checkout Session и сохраняем **её id** в PENDING-транзакцию;<br>— при автосписаниях сохраняем `invoice.id` как «сессионный» ID                                                    | Создание PENDING: `TransactionService.makePayment` (ветка STRIPE) → `createTransaction({ stripeSessionId: session.id })`.<br>Автосписания: `handleInvoicePaymentSucceeded/Failed` → `createTransaction({ stripeSessionId: invoice.id })`                                                                                        |
| `status` `TransactionStatus @default(PENDING)` | Текущий статус транзакции                                                        | Начально `PENDING` при создании; далее меняется по вебхукам на `SUCCESS`/`FAILED`/`EXPIRED`                                                                                                                                                | Создание: `TransactionCommandRepository.createTransaction`.<br>Апдейты Stripe: `WebhookStripeService.handleSuccess/Failed/Expired...` через `transactionService.updateTransaction`.<br>Апдейты PayPal: `WebhookPaypalService.handlePaymentCompleted/Failed` (либо update существующей PENDING, либо создание новой транзакции). |
| `paypalSessionId` `String?`                    | Внешний ID платежа/события PayPal (из `resource.id`)                             | **PayPal:**<br>— при первой успешной/неуспешной оплате, если исходная PENDING ещё без `paypalSessionId`, ставим его в апдейте;<br>— при автопродлениях — создаём **новую** транзакцию с этим `paypalSessionId`                             | Обновление/создание: `WebhookPaypalService.handlePaymentCompleted` / `handlePaymentFailed`                                                                                                                                                                                                                                      |
| `paypalPlanId` `String?`                       | ID плана в PayPal (из `resource.plan_id`)                                        | **PayPal:** пишется одновременно с `paypalSessionId`                                                                                                                                                                                       | Там же: `WebhookPaypalService.handlePaymentCompleted/Failed`                                                                                                                                                                                                                                                                    |
| `createdAt` `DateTime @default(now())`         | Когда мы считаем платёж «совершённым/попытка»                                    | **Stripe:**<br>— первый платёж: `new Date(session.created * 1000)` в апдейте транзакции;<br>— автосписания: `new Date(invoice.period_start * 1000)` при создании новой транзакции.<br>**PayPal:** `new Date(resource.create_time)`         | Stripe: `WebhookStripeService.handleSuccessCheckoutSession` (update) и `handleInvoicePaymentSucceeded/Failed` (create).<br>PayPal: `WebhookPaypalService.handlePaymentCompleted/Failed`                                                                                                                                         |
| `expiresAt` `DateTime?`                        | До какой даты действует текущая оплаченная подписка **в рамках этой транзакции** | **Stripe:**<br>— первый платёж: `startedAt + planIntervalsInDays[plan.interval]`;<br>— автосписания: по `invoice.period_end`.<br>**PayPal:** аналогично по `resource.create_time` + интервал плана                                         | Stripe: `handleSuccessCheckoutSession` (update) и `handleInvoicePaymentSucceeded/Failed` (create).<br>PayPal: `handlePaymentCompleted/Failed`                                                                                                                                                                                   |
| `expiresLinkAt` `DateTime?`                    | Срок «годности» платёжной ссылки (для EXPIRED)                                   | Ставится при создании транзакции как `now + 24h`. Далее крон помечает такие PENDING как `EXPIRED` после истечения                                                                                                                          | Установка: `TransactionCommandRepository.createTransaction`.<br>Крон: `TransactionService.changeStatusOfExpiredTransactions` → `transactionCommandRepository.changeStatusOfExpiredTransactions`                                                                                                                                 |
| `provider` `TransactionProvider`               | Какой провайдер: `STRIPE` / `PAYPAL`                                             | Ставится при создании транзакции исходя из `payment.provider`                                                                                                                                                                              | Создание: `TransactionCommandRepository.createTransaction` (через DTO из `TransactionService.makePayment`)                                                                                                                                                                                                                      |
| `userId` `String`                              | Внутренний ID пользователя (из нашего Auth)                                      | Пишется при создании транзакции                                                                                                                                                                                                            | Там же                                                                                                                                                                                                                                                                                                                          |

*/