apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: TCP_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: TCP_PORT
             - name: SMTP_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: SMTP_PORT
             - name: SMTP_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: SMTP_HOST
             - name: SMTP_USER
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: SMTP_USER
             - name: SMTP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: SMTP_PASSWORD
             - name: FRONTEND_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: FRONTEND_URL
             - name: TCP_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-notifications-production-config-secret
                   key: TCP_HOST
