export enum WebsocketEvents {
	NEW_NOTIFICATION = "NEW_NOTIFICATION",
	SUBSCRIBE_NOTIFICATIONS = "SUBSCRIBE_NOTIFICATIONS",
	ERROR = "ERROR",
	TEST_NOTIFICATION = "TEST_NOTIFICATION",
	SUBSCRIBE_CHAT = "SUBSCRIBE_CHAT",
	NEW_MESSAGE = "NEW_MESSAGE",
	SEND_MESSAGE = "SEND_MESSAGE",
	SUBSCRIBE_ALL_ROOM_MESSAGES = "SUBSCRIBE_ALL_ROOM_MESSAGES",
	NEW_GLOBAL_MESSAGE = "NEW_GLOBAL_MESSAGE",
}
