export enum OutboxEventStatuses {
	PENDING = "PENDING",
	PUBLISHED = "PUBLISHED",
	FAILED = "FAILED",
}

export enum INBOX_STATUS {
	RECEIVED = "RECEIVED",
	PROCESSED = "PROCESSED",
	FAILED = "FAILED",
}

export enum OUTBOX_STATUS {
	PENDING = "PENDING",
	PUBLISHED = "PUBLISHED",
	PROCESSED = "PROCESSED",
	FAILED = "FAILED",
}
